services:
  kirakira-frontend:
    # Frontend
    container_name: kirakira-frontend
    image: kirakira-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Expose port for host Nginx
    ports:
      - "3003:3003"
    restart: unless-stopped

  kirakira-backend:
    # Backend (FastAPI)
    container_name: kirakira-backend
    image: kirakira-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://kirakira:kirakira123@172.20.0.1:5432/kirakira
      - FRONTEND_URL=https://kirakira.cukee.world
    volumes:
      - uploads_data:/app/uploads
      - ./backend:/app
    restart: unless-stopped

volumes:
  uploads_data:
